const { contextBridge, ipcRenderer } = require('electron');
const on = (ch, fn) => ipcRenderer.on(ch, (_e, ...a) => fn(...a));
contextBridge.exposeInMainWorld('api', {
  // bar
  setSize: (w, h) => ipcRenderer.send('bar:size', w, h),
  dragStart: () => ipcRenderer.send('bar:dragStart'),
  dragEnd: () => ipcRenderer.send('bar:dragEnd'),
  onAnchor: fn => on('bar:anchor', fn),
  capture: kind => ipcRenderer.send('capture:start', kind),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: p => ipcRenderer.invoke('settings:set', p),
  pickDir: () => ipcRenderer.invoke('settings:pickDir'),
  quit: () => ipcRenderer.send('app:quit'),
  minimize: () => ipcRenderer.send('app:minimize'),
  checkUpdates: () => ipcRenderer.send('app:checkUpdates'),
  installUpdate: () => ipcRenderer.send('app:installUpdate'),
  recOpen: ext => ipcRenderer.invoke('rec:open', ext),
  recChunk: buf => ipcRenderer.invoke('rec:chunk', buf),
  recFinish: o => ipcRenderer.invoke('rec:finish', o),
  recCapturing: () => ipcRenderer.send('rec:capturing'),
  recState: r => ipcRenderer.send('rec:state', r),
  onSpeed: fn => on('speed:set', fn),
  onSettingsChanged: fn => on('settings:changed', fn),
  onRenderProgress: fn => on('render:progress', fn),
  cancelBake: () => ipcRenderer.send('rec:cancelBake'),
  cancelBake: () => ipcRenderer.send('rec:cancelBake'),
  moveFile: f => ipcRenderer.invoke('file:move', f),
  reveal: f => ipcRenderer.send('file:reveal', f),
  deleteFile: f => ipcRenderer.send('file:delete', f),
  copyImage: f => ipcRenderer.send('file:copyImage', f),
  copyPath: f => ipcRenderer.send('file:copyPath', f),
  onRecStart: fn => on('rec:start', fn),
  onResult: fn => on('result', fn),
  onError: fn => on('error', fn),
  onUpdate: fn => on('update', fn),
  onZoom: fn => on('zoom:state', fn),
  // select overlay
  selectDone: r => ipcRenderer.send('select:done', r),
  // zoom overlay
  zoomHide: () => ipcRenderer.send('zoom:hide'),
  perf: (name, data) => ipcRenderer.send('perf', name, data),
  onOverlayInit: fn => on('overlay:init', fn),
  onBox: fn => on('box', fn),
  onHud: fn => on('hud', fn),
  onAnno: fn => on('anno', fn),
});
